### ISSUE TITLE
Amplitude ceiling setting is saved but not readable 

### ISSUE THREAD

**Issue by aria1th** [FracturedCode/XpBeacons#12]
How to reproduce:
set Amplitude setting (i.e. strength_amplitude_ceiling) to 20 and save as setDefault.
It is applied until server reboot.

when you reboot server, you'll see this and setting is ignored and deleted:
[19:39:35] [Server thread/ERROR]: [CM]: The value of 20 for strength_amplitude_ceiling(Experience Beacons) is not valid - ignoring...

Carpet base version : 1.18-1.4.56
XpBeacons - 1.18-7.0

**Comment by FracturedCode** [comment]
#13
> I think I will wait for 1.18.2 and carpet before creating a release. Thank you for your contribution.

Until then, anyone who wants a fix for this issue can compile their own from the dev branch. Just change some of the `gradle.properties` and `fabric.mod.json`

**Comment by FracturedCode** [comment]
Fixed with [release 7.1](https://github.com/FracturedCode/XpBeacons/releases/tag/7.1)
