### ISSUE TITLE
wiki broke

### ISSUE THREAD

**Issue by clmc99** [FracturedCode/XpBeacons#16]
The [wiki link](https://urlsl.me/xpBeaconsWiki) and official website both appear to be down. Wayback Machine has not archived either.

**Comment by FracturedCode** [comment]
Sorry about that. My projects have been in a state of flux as I am overhauling my infra. Please use the github wiki instead for now
https://github.com/FracturedCode/XpBeacons/wiki/Features

**Comment by FracturedCode** [comment]
I brought it back, but it will almost certainly crash again.

**Comment by FracturedCode** [comment]
The wiki host has been stable for awhile now. Closing.
