### ISSUE TITLE
Doesn't Work Properly on Servers

### ISSUE THREAD

**Issue by IAmSneak** [FracturedCode/XpBeacons#2]
When used on a server, the mod loads but the command doesn't work. The carpet command exists and is set to true. Sometimes I am able to use the mod on the server, but this is uncommon. I also do not get increased effects from having high levels when the command does not exist.

**Comment by FracturedCode** [comment]
I'll take a look at it today. Thinking back I didn't really design this mod with servers in mind, but my guess would be it wouldn't be difficult to support that.

**Comment by FracturedCode** [comment]
> 
> 
> When used on a server, the mod loads but the command doesn't work. The carpet command exists and is set to true. Sometimes I am able to use the mod on the server, but this is uncommon. I also do not get increased effects from having high levels when the command does not exist.

Hello, could you give me your server _and_ client mod list? I just tried it on a server with and without the mod installed on the client and got the expected results. Normally I would ask if you've tried like **really** high levels ie 10000 or above, but you implied that sometimes it works and sometimes it doesn't. Do you have any useful server log output as well?

**Comment by FracturedCode** [comment]
I was able to reproduce the bug where the command does not exist, but the functionality was still there.

**Comment by Jobieskii** [comment]
I have the same problem, where the functionality is there but the command isn't (on a server). Any updates on that?
Side note, would it be possible to add a config file alongside the command?

**Comment by FracturedCode** [comment]
> 
> 
> I have the same problem, where the functionality is there but the command isn't (on a server). Any updates on that?
> Side note, would it be possible to add a config file alongside the command?

Yes, I just fixed it.

 The config is handled by carpet. When you use `/carpet setDefault xpbeacons true` or `/xpbeacons setDefault haste_amplitude_ceiling 11`, for instance, it should save in `carpet.conf` and `xpbeacons.conf`, respectively.

Thanks for your interest in the project. There is now 1.17 support with v4.0
