### ISSUE TITLE
Regen multiplier is affected by primary effect

### ISSUE THREAD

**Issue by IAmSneak** [FracturedCode/XpBeacons#4]
This is because in getEffectSpecificAmplificationMultiplier() it doesn't take into account the variable put in and instead always bases its checks on the primary effect. This can be fixed with replacing

            if (effectsInOrder[i].equals(this.primary)) {

with

            if (effectsInOrder[i].equals(se)) {
            
If I can figure out how to open a PR I can request one that fixes the two reports I have opened.

**Comment by FracturedCode** [comment]
Yeah, I hated that mixin, so I nuked it. Check out release 4.0 for a much better *experience* (see what I did there)
